// PRODUCT
export const FETCH_PRODUCT_STARTED = "FETCH_PRODUCT_STARTED";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

export const ADD_PRODUCT_STARTED = "ADD_PRODUCT_STARTED";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const GET_PRODUCT_STARTED = "GET_PRODUCT_STARTED";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

// CATEGORIES
export const FETCH_CATEGORY_STARTED = "FETCH_CATEGORY_STARTED";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const ADD_CATEGORY_STARTED = "ADD_CATEGORY_STARTED";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const INCREMENT_ITEM = "INCREMENT_ITEM";
export const DECREMENT_ITEM = "DECREMENT_ITEM";

// AUTH
export const AUTH_STARTED = "AUTH_STARTED";
export const SET_AUTH = "SET_AUTH";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

// NEWS
export const FETCH_NEWS_STARTED = "FETCH_NEWS_STARTED";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";

export const ADD_NEWS_STARTED = "ADD_NEWS_STARTED";
export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS";

export const GET_SINGLE_NEWS_STARTED = "GET_SINGLE_NEWS_STARTED";
export const GET_SINGLE_NEWS_SUCCESS = "GET_SINGLE_NEWS_SUCCESS";

export const NEWS_FAILURE = "NEWS_FAILURE";

// ORDERS
export const ORDER_ACTION_STARTED = "ORDER_ACTION_STARTED";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SINGLE_ORDER_SUCCESS = "SINGLE_ORDER_SUCCESS";

export const ORDER_ACTION_FAILURE = "ORDER_ACTION_FAILURE";
